# Generated by Django 4.0.5 on 2023-06-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
